
import React from 'react';
import Section from '../components/Section';

const IntroductionView: React.FC = () => {
  return (
    <div>
      <header className="mb-12 text-center">
        <h1 className="text-5xl font-extrabold text-primary-text mb-2">
          Cryptocurrency System Using Body Activity Data
        </h1>
        <p className="text-xl text-secondary-text">
          An analysis of Patent <span className="font-mono text-accent">WO 2020/060606 A1</span>
        </p>
      </header>
      
      <Section title="Abstract">
        <p className="text-lg text-secondary-text leading-relaxed">
          The patent describes a system where human body activity, associated with a task provided to a user, can be used in the mining process of a cryptocurrency. A server provides a task to a user's device. A sensor, either coupled to or part of the user's device, senses the user's body activity. This body activity data is then generated and sent to the cryptocurrency system. The system verifies if the data satisfies one or more predefined conditions and, if verified, awards cryptocurrency to the user.
        </p>
      </Section>

      <Section title="Core Problem & Proposed Solution">
        <div className="space-y-4 text-secondary-text leading-relaxed">
          <p>
            <strong className="text-primary-text">Problem:</strong> Traditional cryptocurrency mining, particularly proof-of-work systems like Bitcoin's, requires enormous amounts of computational energy. This process involves computers solving computationally difficult problems, which is slow, energy-intensive, and has a significant environmental impact.
          </p>
          <p>
            <strong className="text-primary-text">Solution:</strong> This patent proposes replacing the massive computational work with a "proof-of-work" generated by human body activity. Instead of a computer burning energy on calculations, a user performs a task (e.g., viewing an ad, using a service). The user's subconscious body activity (like brain waves or body heat) generated during this task is measured. This data, which is difficult to consciously fake, serves as proof that a "computationally difficult problem" has been solved by a human. The stated goal is to reduce computational energy consumption and make the mining process faster and more accessible.
          </p>
        </div>
      </Section>
    </div>
  );
};

export default IntroductionView;
